// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXP6L4fVqB_IQC4Vna3CIUpLz_oo-pbbg',
    appId: '1:421447636804:web:64c87d6da10e212624a911',
    messagingSenderId: '421447636804',
    projectId: 'aryasm-bd5a4',
    authDomain: 'aryasm-bd5a4.firebaseapp.com',
    storageBucket: 'aryasm-bd5a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbkFehC9PRdK2uD6gSeTxEfqHDTRUnBg',
    appId: '1:421447636804:android:5669acb967db620924a911',
    messagingSenderId: '421447636804',
    projectId: 'aryasm-bd5a4',
    storageBucket: 'aryasm-bd5a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kDAWupaeoE1HIAiab33qYiauty1pKzo',
    appId: '1:421447636804:ios:19d78fc4c5a509df24a911',
    messagingSenderId: '421447636804',
    projectId: 'aryasm-bd5a4',
    storageBucket: 'aryasm-bd5a4.appspot.com',
    iosBundleId: 'com.example.khrchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-kDAWupaeoE1HIAiab33qYiauty1pKzo',
    appId: '1:421447636804:ios:7e4bed55885f1b1e24a911',
    messagingSenderId: '421447636804',
    projectId: 'aryasm-bd5a4',
    storageBucket: 'aryasm-bd5a4.appspot.com',
    iosBundleId: 'com.example.khrchApp.RunnerTests',
  );
}
